import { NextRequest, NextResponse } from 'next/server';
import { currentUser } from '@clerk/nextjs/server';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';

export async function POST(request: NextRequest) {
  try {
    const user = await currentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { content, title } = await request.json();

    if (!content) {
      return NextResponse.json({ error: 'Content is required' }, { status: 400 });
    }

    // Parse content into paragraphs
    const lines = content.split('\n').filter((line: string) => line.trim() !== '');
    
    const docParagraphs = lines.map((line: string) => {
      // Check if line is a heading (all caps or starts with number)
      const isHeading = /^[A-Z\s]+$/.test(line.trim()) || /^\d+\./.test(line.trim());
      
      if (isHeading) {
        return new Paragraph({
          children: [
            new TextRun({
              text: line,
              bold: true,
              size: 24,
            }),
          ],
          heading: HeadingLevel.HEADING_2,
          spacing: {
            before: 200,
            after: 200,
          },
        });
      } else {
        return new Paragraph({
          children: [
            new TextRun({
              text: line,
              size: 22,
            }),
          ],
          spacing: {
            after: 120,
          },
        });
      }
    });

    // Add watermark for free users
    // TODO: Check user subscription tier
    const isFreeTier = true; // This should come from database
    if (isFreeTier) {
      docParagraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: '\n\nGenerated by LegalDraft AI - Upgrade to remove this watermark',
              size: 16,
              color: '808080',
              italics: true,
            }),
          ],
        })
      );
    }

    // Create document
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text: title || 'Legal Document',
                  bold: true,
                  size: 32,
                }),
              ],
              heading: HeadingLevel.TITLE,
              spacing: {
                after: 400,
              },
            }),
            ...docParagraphs,
          ],
        },
      ],
    });

    // Generate DOCX buffer
    const buffer = await Packer.toBuffer(doc);

    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${title || 'document'}.docx"`,
      },
    });

  } catch (error) {
    console.error('Error generating DOCX:', error);
    return NextResponse.json(
      { error: 'Failed to generate DOCX' },
      { status: 500 }
    );
  }
}