import { NextRequest, NextResponse } from 'next/server';
import { currentUser } from '@clerk/nextjs/server';
import jsPDF from 'jspdf';

export async function POST(request: NextRequest) {
  try {
    const user = await currentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { content, title } = await request.json();

    if (!content) {
      return NextResponse.json({ error: 'Content is required' }, { status: 400 });
    }

    // Create PDF
    const doc = new jsPDF();
    
    // Set font and title
    doc.setFontSize(16);
    doc.text(title || 'Legal Document', 20, 20);
    
    // Add content
    doc.setFontSize(12);
    const lines = doc.splitTextToSize(content, 170);
    doc.text(lines, 20, 40);
    
    // Add footer with watermark for free users
    // TODO: Check user subscription tier
    const isFreeTier = true; // This should come from database
    if (isFreeTier) {
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text('Generated by LegalDraft AI - Upgrade to remove this watermark', 20, 280);
    }

    // Generate PDF buffer
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${title || 'document'}.pdf"`,
      },
    });

  } catch (error) {
    console.error('Error generating PDF:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}