import { Document, Packer, Paragraph, TextRun } from 'docx';
import { saveAs } from 'file-saver';

export async function exportToDOCX(content: string, fileName: string, addWatermark: boolean = false) {
  const paragraphs: Paragraph[] = [];

  // Add watermark text if needed
  if (addWatermark) {
    paragraphs.push(
      new Paragraph({
        children: [
          new TextRun({
            text: 'Generated by LegalDraft AI',
            color: 'CCCCCC',
            size: 16,
          }),
        ],
      }),
      new Paragraph({ text: '' }) // Empty line
    );
  }

  // Split content into paragraphs
  const lines = content.split('\n');
  
  lines.forEach((line) => {
    if (line.trim() === '') {
      paragraphs.push(new Paragraph({ text: '' }));
    } else {
      // Check if it's a header (ALL CAPS or numbered section)
      const isHeader = line === line.toUpperCase() || /^\d+\./.test(line.trim());
      
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: line,
              bold: isHeader,
              size: isHeader ? 24 : 22,
            }),
          ],
        })
      );
    }
  });

  const doc = new Document({
    sections: [
      {
        children: paragraphs,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, fileName);
}
